name: Deploy to Firebase

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: pnpm/action-setup@v2
      with:
        version: latest
    - run: pnpm i
    - run: pnpm build
    - run: pnpm run deploy --token ${{ secrets.firebaseToken }}
